### ISSUE TITLE
Adding multiple libraries

### ISSUE THREAD

**Issue by szkiba** [k6io/jslib.k6.io#34]
Hi k6 Team,

I'm going to add a few JavaScript library and open a PR, but before do that, I'd like to know what is your preference: should I create separated PRs for each of them or is it ok to open only one PR?
The libraries I'm going to add:
https://www.npmjs.com/package/jmespath
https://www.npmjs.com/package/url-template
https://www.npmjs.com/package/qs

Have you any concern about these libraries?

(I already checked the README, and did a quick try how to add a new library)

BR
Iván

**Comment by simskij** [comment]
Multiple are definitely prefered to avoid long review processes 👍🏽

**Comment by szkiba** [comment]
Hi @simskij , finally I changed my mind, and I'd like to add only add one library :)
https://github.com/k6io/jslib.k6.io/pull/35
